jobs:
  run-jdk-compatibility-and-windows:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh workflow run main.yml -f jdk_compatibility_ci=true -f windows_ci=true
        --repo ${GITHUB_REPOSITORY}
name: daily
on:
  repository_dispatch:
    types: trigger-ga___daily.yml
permissions:
  actions: write
