jobs:
  triage:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Add agent-java label
      uses: actions/github-script@v7
      with:
        script: "github.rest.issues.addLabels({\n  issue_number: context.issue.number,\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  labels: [\"\
          agent-java\"]\n})\n"
    - continue-on-error: true
      id: is_elastic_member
      uses: elastic/apm-pipeline-library/.github/actions/is-member-elastic-org@current
      with:
        token: ${{ secrets.APM_TECH_USER_TOKEN }}
        username: ${{ github.actor }}
    - continue-on-error: true
      if: contains(steps.is_elastic_member.outputs.result, 'false') && github.actor
        != 'dependabot[bot]'
      name: Add community and triage lables
      uses: actions/github-script@v7
      with:
        script: "github.rest.issues.addLabels({\n  issue_number: context.issue.number,\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  labels: [\"\
          community\", \"triage\"]\n})\n"
    - continue-on-error: true
      if: contains(steps.is_elastic_member.outputs.result, 'false') && github.actor
        != 'dependabot[bot]'
      name: Add comment for community PR
      uses: wow-actions/auto-comment@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        pullRequestOpened: "\U0001F44B @{{ author }} Thanks a lot for your contribution!\
          \ \n\nIt may take some time before we review a PR, so even if you don\u2019\
          t see activity for some time, it **does not** mean that we have forgotten\
          \ about it. \n\nEvery once in a while we go through a process of prioritization,\
          \ after which we are focussing on the tasks that were planned for the upcoming\
          \ [milestone](https://github.com/elastic/apm-agent-java/milestones). The\
          \ prioritization status is typically reflected through the PR labels. It\
          \ could be pending triage, a candidate for a future milestone, or have a\
          \ target milestone set to it.\n"
    - continue-on-error: true
      env:
        MY_GITHUB_TOKEN: ${{ secrets.APM_TECH_USER_TOKEN }}
      if: contains(steps.is_elastic_member.outputs.result, 'true') && github.event.pull_request
      name: Assign new internal pull requests to project
      uses: elastic/assign-one-project-github-action@1.2.2
      with:
        column_name: In Progress
        project: https://github.com/orgs/elastic/projects/454
        project_id: '5882982'
name: Issue Labeler
on:
  repository_dispatch:
    types: trigger-ga___labeler.yml
permissions:
  contents: read
  issues: write
  pull-requests: write
