jobs:
  app-server-integration-tests:
    name: Application Server integration tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: echo "Not required for docs"
  non-app-server-integration-tests:
    name: Non-Application Server integration tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: echo "Not required for docs"
name: main
on:
  repository_dispatch:
    types: trigger-ga___main-docs.yml
permissions:
  contents: read
