concurrency:
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  app-server-integration-tests:
    if: 'contains(github.event.pull_request.labels.*.name, ''ci:agent-integration'')

      || github.event.pull_request.draft == false

      || inputs.agent_integration_tests_ci == true

      '
    name: Application Server integration tests
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ./.github/workflows/unstash
      with:
        name: build
        path: ${{ github.workspace }}
    - continue-on-error: true
      name: Free Disk Space
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
      with:
        android: true
        docker-images: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true
        tool-cache: false
    - continue-on-error: true
      uses: ./.github/workflows/maven-goal
      with:
        command: ./mvnw -q -P ci-application-server-integration-tests verify
    - continue-on-error: true
      if: success() || failure()
      name: Store test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-app-server-integration
        path: '**/junit-*.xml

          **/TEST-*.xml

          '
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ./.github/workflows/maven-goal
      with:
        command: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true
    - continue-on-error: true
      uses: ./.github/workflows/stash
      with:
        name: build
        path: ${{ github.workspace }}
    - continue-on-error: true
      name: Upload agent binaries as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: elastic-apm-agent
        path: './elastic-apm-agent/target/elastic-apm-agent-*.jar

          !./**/*-sources.jar

          '
    - continue-on-error: true
      name: Upload agent java 8 binaries as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: elastic-apm-agent-java8
        path: './elastic-apm-agent-java8/target/elastic-apm-agent-java8-*.jar

          !./**/*-sources.jar

          '
    - continue-on-error: true
      name: Upload agent attach CLI artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apm-agent-attach-cli
        path: './apm-agent-attach-cli/target/apm-agent-attach-cli-*.jar

          !./**/*-sources.jar

          !./**/*-tests.jar

          '
    - continue-on-error: true
      name: Upload agent attach artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apm-agent-attach
        path: './apm-agent-attach/target/apm-agent-attach-*.jar

          !./**/*-sources.jar

          '
    - continue-on-error: true
      name: Upload agent API artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apm-agent-api
        path: './apm-agent-api/target/apm-agent-api-*.jar

          !./**/*-sources.jar

          '
    - continue-on-error: true
      name: Upload agent plugin SDK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apm-agent-plugin-sdk
        path: './apm-agent-plugin-sdk/target/apm-agent-plugin-sdk-*.jar

          !./**/*-sources.jar

          '
    - continue-on-error: true
      name: Upload benchmark binaries as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apm-agent-benchmarks
        path: './apm-agent-benchmarks/target/benchmarks*.jar

          !./**/*-sources.jar

          '
  javadoc:
    name: Javadoc
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ./.github/workflows/unstash
      with:
        name: build
        path: ${{ github.workspace }}
    - continue-on-error: true
      uses: ./.github/workflows/maven-goal
      with:
        command: ./mvnw compile javadoc:javadoc
  jboss:
    if: github.event_name != 'pull_request' || ( github.event_name == 'pull_request'
      && github.event.pull_request.head.repo.fork == false && github.actor != 'dependabot[bot]'
      )
    name: JBoss integration tests
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: elastic/apm-pipeline-library/.github/actions/docker-login@current
      with:
        registry: docker.elastic.co
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secret: secret/observability-team/ci/docker-registry/prod
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        url: ${{ secrets.VAULT_ADDR }}
    - continue-on-error: true
      uses: ./.github/workflows/unstash
      with:
        name: build
        path: ${{ github.workspace }}
    - continue-on-error: true
      name: Pull JBoss docker images
      run: .ci/scripts/jboss-pull.sh
    - continue-on-error: true
      uses: ./.github/workflows/maven-goal
      with:
        command: ./mvnw -q -P ci-jboss-integration-tests verify
    - continue-on-error: true
      if: success() || failure()
      name: Store test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-jboss-integration
        path: '**/junit-*.xml

          **/TEST-*.xml

          '
  jdk-compatibility-tests:
    if: 'contains(github.event.pull_request.labels.*.name, ''ci:jdk-compatibility'')

      || inputs.jdk_compatibility_ci == true

      '
    name: JDK Compatibility Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ./.github/workflows/maven-goal-jdk
      with:
        command: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true
        test-java-distribution: ${{ matrix.distribution }}
        test-java-version: ${{ matrix.version }}
    - continue-on-error: true
      name: Run tests for ${{ matrix.version }}:${{ matrix.distribution }}
      run: ./mvnw test -Delastic.jdkCompatibilityTest=true -Dtest_java_binary=${{
        env.TEST_JAVA_BINARY }}
    - continue-on-error: true
      if: success() || failure()
      name: Store test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-jdk-compatibility-${{ matrix.version }}-${{ matrix.distribution
          }}
        path: '**/junit-*.xml

          **/TEST-*.xml

          '
    strategy:
      fail-fast: false
      matrix:
        include:
        - distribution: temurin
          version: 11
        - distribution: temurin
          version: 17
        - distribution: temurin
          version: 21
        - distribution: temurin
          version: 22-ea
  license:
    name: License
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ./.github/workflows/unstash
      with:
        name: build
        path: ${{ github.workspace }}
    - continue-on-error: true
      name: install artifacts
      uses: ./.github/workflows/maven-goal
      with:
        command: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true
    - continue-on-error: true
      name: mvn license
      run: ./mvnw org.codehaus.mojo:license-maven-plugin:aggregate-third-party-report
        -Dlicense.excludedGroups=^co\\.elastic\\.
  non-app-server-integration-tests:
    if: 'contains(github.event.pull_request.labels.*.name, ''ci:agent-integration'')

      || github.event.pull_request.draft == false

      || inputs.agent_integration_tests_ci == true

      '
    name: Non-Application Server integration tests
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ./.github/workflows/unstash
      with:
        name: build
        path: ${{ github.workspace }}
    - continue-on-error: true
      name: Free Disk Space
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
      with:
        android: true
        docker-images: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true
        tool-cache: false
    - continue-on-error: true
      uses: ./.github/workflows/maven-goal
      with:
        command: ./mvnw -q -P ci-non-application-server-integration-tests verify
    - continue-on-error: true
      if: success() || failure()
      name: Store test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-non-app-server-integration
        path: '**/junit-*.xml

          **/TEST-*.xml

          '
  unit-tests:
    if: inputs.test_ci == true || inputs.test_ci == null
    name: Unit Tests
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ./.github/workflows/unstash
      with:
        name: build
        path: ${{ github.workspace }}
    - continue-on-error: true
      uses: ./.github/workflows/maven-goal
      with:
        command: ./mvnw test -DargLine="-Delastic.apm.overwrite.config.docs=false"
    - continue-on-error: true
      if: success() || failure()
      name: Store test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-JUnit
        path: '**/junit-*.xml

          **/TEST-*.xml

          '
  unit-tests-windows:
    if: "(inputs.test_ci == true || inputs.test_ci == null)\n&& (contains(github.event.pull_request.labels.*.name,\
      \ 'ci:windows')\n  || inputs.windows_ci == true)\n"
    name: Build & Test Windows
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Support longpaths
      run: git config --system core.longpaths true
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ./.github/workflows/maven-goal
      with:
        command: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true
    - continue-on-error: true
      name: Run tests
      run: ./mvnw test
    - continue-on-error: true
      if: success() || failure()
      name: Store test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-windows
        path: '**/junit-*.xml

          **/TEST-*.xml

          '
name: main
on:
  repository_dispatch:
    types: trigger-ga___main.yml
permissions:
  contents: read
