jobs:
  microbenchmark:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        JAVA_VERSION: ${{ inputs.java_version || 'openjdk-17+35-linux' }}
      id: buildkite
      name: Run buildkite pipeline
      uses: elastic/apm-pipeline-library/.github/actions/buildkite@current
      with:
        buildEnvVars: 'script=.ci/scripts/bench.sh

          repo=apm-agent-java

          sha=${{ github.sha }}

          JAVA_VERSION=${{ env.JAVA_VERSION }}

          BRANCH_NAME=${{ github.ref_name }}

          '
        pipeline: apm-agent-microbenchmark
        printBuildLogs: true
        triggerMessage: ${{ github.repository }}@${{ github.ref_name }}
        vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
        vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
        vaultUrl: ${{ secrets.VAULT_ADDR }}
        waitFor: true
    - continue-on-error: true
      if: ${{ failure() }}
      uses: elastic/apm-pipeline-library/.github/actions/slack-message@current
      with:
        channel: '#apm-agent-java'
        message: ':ghost: [${{ github.repository }}] microbenchmark *${{ github.ref_name
          }}* failed to run in Buildkite.

          Build: (<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{
          github.run_id }}|here>)

          '
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        url: ${{ secrets.VAULT_ADDR }}
    timeout-minutes: 60
name: microbenchmark
on:
  repository_dispatch:
    types: trigger-ga___microbenchmark.yml
permissions:
  contents: read
