jobs:
  otel-export-trace:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: elastic/apm-pipeline-library/.github/actions/opentelemetry@current
      with:
        vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
        vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
        vaultUrl: ${{ secrets.VAULT_ADDR }}
name: OpenTelemetry Export Trace
on:
  repository_dispatch:
    types: trigger-ga___opentelemetry.yml
permissions:
  contents: read
