jobs:
  upload:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ./.github/workflows/maven-goal
      with:
        command: ./mvnw clean install -DskipTests=true -Dmaven.javadoc.skip=true
    - continue-on-error: true
      name: Publish snaphosts
      uses: elastic/apm-pipeline-library/.github/actions/snapshoty-simple@current
      with:
        config: .ci/snapshoty.yml
        vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
        vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
        vaultUrl: ${{ secrets.VAULT_ADDR }}
name: Snapshoty
on:
  repository_dispatch:
    types: trigger-ga___snapshoty.yml
