jobs:
  report:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: elastic/apm-pipeline-library/.github/actions/test-report@current
      with:
        artifact: /test-results-(.*)/
        name: Test Results $1
        path: '**/*.xml'
        reporter: java-junit
name: test-reporter
on:
  repository_dispatch:
    types: trigger-ga___test-reporter.yml
permissions:
  actions: read
  checks: write
  contents: read
